version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: pharmacy_management
    ports:
      - "3310:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8000:80"
    depends_on:
      - mysql
  back_prod:
    build: .
    container_name: back_prod
    restart: always
    ports:
    - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/pharmacy_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SERVER_PORT: 8081
    depends_on:
     - mysql
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: front
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - back_prod